(**************************************************************************)
(*                                                                        *)
(*     Alt-Ergo: The SMT Solver For Software Verification                 *)
(*     Copyright (C) --- OCamlPro SAS                                     *)
(*                                                                        *)
(*     This file is distributed under the terms of OCamlPro               *)
(*     Non-Commercial Purpose License, version 1.                         *)
(*                                                                        *)
(*     As an exception, Alt-Ergo Club members at the Gold level can       *)
(*     use this file under the terms of the Apache Software License       *)
(*     version 2.0.                                                       *)
(*                                                                        *)
(*     ---------------------------------------------------------------    *)
(*                                                                        *)
(*     More details can be found in the directory licenses/               *)
(*                                                                        *)
(**************************************************************************)

module E = Expr
module Sy = Symbols
module Ex = Explanation
module Q = Numbers.Q
module Z = Numbers.Z
module Names = E.FP.Names

let src = Logs.Src.create ~doc:"Fpa_rel" __MODULE__

module Log = (val Logs.src_log src : Logs.LOG)

let timer = Timers.M_None

module IntPairSet = Set.Make (struct
  type t = int * int

  let compare (a1, b1) (a2, b2) =
    let c = Int.compare a1 a2 in
    if c <> 0 then c else Int.compare b1 b2
end)

(* Literals needed by the FPA theory axioms generated by why3 *)
type precision_literals =
  { max_int_z : Z.t;
    pow2sb : Z.t;
    half_pow2sb : Z.t;
    abs_err_rne_denom : Z.t;
    abs_err_denom : Z.t
  }

(* New instances of the Float(eb, sb) type and of FPA literals encountered and
   requiring their own fact propagations *)
type t =
  { pending_types : IntPairSet.t;
    pending_literals : (E.t * E.t) list;
    literals_cache : (int * int, precision_literals) Hashtbl.t;
    assumed_preds : Ex.t E.Map.t
  }

let empty uf =
  ( { pending_types = IntPairSet.empty;
      pending_literals = [];
      literals_cache = Hashtbl.create 16;
      assumed_preds = E.Map.empty
    },
    Uf.domains uf )

let pow2 n = Z.shift_left Z.one n

let mk_eq_fact lhs rhs =
  Literal.LTerm (E.mk_eq ~iff:false lhs rhs), Ex.empty, Th_util.Other

(* TODO: cache (eb, sb) -> (eb, sb) exprs? *)
let int_literal_fact eb sb name literal =
  let eb_t = E.Ints.of_int eb in
  let sb_t = E.Ints.of_int sb in
  let lhs = E.mk_term (Sy.name name) [eb_t; sb_t] Ty.Tint in
  mk_eq_fact lhs (E.Ints.of_Z literal)

let real_literal_fact eb sb name literal =
  let eb_t = E.Ints.of_int eb in
  let sb_t = E.Ints.of_int sb in
  let lhs = E.mk_term (Sy.name name) [eb_t; sb_t] Ty.Treal in
  mk_eq_fact lhs (E.Reals.of_Z literal)

let get_literals env eb sb =
  match Hashtbl.find_opt env.literals_cache (eb, sb) with
  | Some c -> c
  | None ->
    let bias = (1 lsl (eb - 1)) - 1 in
    let emax = bias + 1 in
    let min_exp = emax + sb - 3 in
    let c =
      { pow2sb = pow2 sb;
        max_int_z = Z.sub (pow2 emax) (pow2 (emax - sb));
        half_pow2sb = pow2 (sb - 1);
        abs_err_rne_denom = pow2 (min_exp + 1);
        abs_err_denom = pow2 min_exp
      }
    in
    Hashtbl.add env.literals_cache (eb, sb) c;
    c

let type_literal_facts env eb sb =
  let c = get_literals env eb sb in
  [ int_literal_fact eb sb "ae.fp.pow2sb" c.pow2sb;
    int_literal_fact eb sb "ae.fp.max_int" c.max_int_z;
    real_literal_fact eb sb "ae.fp.max_real" c.max_int_z;
    real_literal_fact eb sb "ae.fp.pow2sb_real" c.pow2sb;
    real_literal_fact eb sb "ae.fp.half_pow2sb_real" c.half_pow2sb;
    real_literal_fact eb sb "ae.fp.abs_err_rne_denom" c.abs_err_rne_denom;
    real_literal_fact eb sb "ae.fp.abs_err_denom" c.abs_err_denom ]

let mk_fp_literal_facts eb_t sb_t term ~is_nan ~is_zero ~is_infinite
    ~is_positive ~is_negative =
  let mk_fact name b =
    ( E.mk_term (Sy.name name) [eb_t; sb_t; term] Ty.Tbool,
      if b then E.vrai else E.faux )
  in
  [ mk_fact Names.is_nan is_nan;
    mk_fact Names.is_zero is_zero;
    mk_fact Names.is_infinite is_infinite;
    mk_fact Names.is_positive is_positive;
    mk_fact Names.is_negative is_negative ]

let float_type_params x =
  match E.type_info x with Ty.Tfloat (eb, sb) -> eb, sb | _ -> assert false

let check_fact env condition x =
  let eb, sb = float_type_params x in
  let pred =
    E.mk_term (Sy.name condition)
      [E.Ints.of_int eb; E.Ints.of_int sb; x]
      Ty.Tbool
  in
  E.Map.find_opt pred env.assumed_preds

let mk_fp_eq_literal x fp_val ex =
  let eb, sb = float_type_params x in
  Literal.LTerm (E.mk_eq ~iff:false x (E.float fp_val eb sb)), ex, Th_util.Other

(* TODO: Use domains to store information about which conditions hold for each
   floating-point value? *)
let process_pred env ex t =
  let combine x conditions =
    ( { env with assumed_preds = E.Map.add t ex env.assumed_preds },
      List.filter_map
        (fun (condition, fp_val) ->
          (* If [condition] is true, then x = fp_val *)
          match check_fact env condition x with
          | Some ex2 -> Some (mk_fp_eq_literal x fp_val (Ex.union ex ex2))
          | None ->
            (* TODO: if domains are used, these pending deductions should be
               stored, and propagated if condition becomes true later *)
            None)
        conditions )
  in
  let { E.f; xs; _ } = E.term_view t in
  match xs with
  | [_; _; x] -> begin
    match f with
    | Sy.Name { hs; _ } when String.equal (Hstring.view hs) E.FP.Names.is_nan ->
      env, [mk_fp_eq_literal x Fp_value.NaN ex]
    | Sy.Name { hs; _ } when String.equal (Hstring.view hs) E.FP.Names.is_zero
      ->
      combine x
        [ Names.is_positive, Fp_value.Plus_zero;
          Names.is_negative, Fp_value.Minus_zero ]
    | Sy.Name { hs; _ }
      when String.equal (Hstring.view hs) E.FP.Names.is_infinite ->
      combine x
        [ Names.is_positive, Fp_value.Plus_infinity;
          Names.is_negative, Fp_value.Minus_infinity ]
    | Sy.Name { hs; _ }
      when String.equal (Hstring.view hs) E.FP.Names.is_positive ->
      combine x
        [ Names.is_zero, Fp_value.Plus_zero;
          Names.is_infinite, Fp_value.Plus_infinity ]
    | Sy.Name { hs; _ }
      when String.equal (Hstring.view hs) E.FP.Names.is_negative ->
      combine x
        [ Names.is_zero, Fp_value.Minus_zero;
          Names.is_infinite, Fp_value.Minus_infinity ]
    | _ -> env, []
  end
  | _ -> env, []

let fp_literal_facts eb sb term v =
  let eb_t = E.Ints.of_int eb in
  let sb_t = E.Ints.of_int sb in
  match v with
  | Fp_value.NaN ->
    mk_fp_literal_facts eb_t sb_t term ~is_nan:true ~is_zero:false
      ~is_infinite:false ~is_positive:false ~is_negative:false
  | Plus_infinity ->
    mk_fp_literal_facts eb_t sb_t term ~is_nan:false ~is_zero:false
      ~is_infinite:true ~is_positive:true ~is_negative:false
  | Minus_infinity ->
    mk_fp_literal_facts eb_t sb_t term ~is_nan:false ~is_zero:false
      ~is_infinite:true ~is_positive:false ~is_negative:true
  | Plus_zero ->
    mk_fp_literal_facts eb_t sb_t term ~is_nan:false ~is_zero:true
      ~is_infinite:false ~is_positive:true ~is_negative:false
  | Minus_zero ->
    mk_fp_literal_facts eb_t sb_t term ~is_nan:false ~is_zero:true
      ~is_infinite:false ~is_positive:false ~is_negative:true
  | Finite q ->
    let to_real_term =
      E.mk_term (Sy.name Names.to_real) [eb_t; sb_t; term] Ty.Treal
    in
    (to_real_term, E.Reals.of_Q q)
    :: mk_fp_literal_facts eb_t sb_t term ~is_nan:false ~is_zero:false
         ~is_infinite:false
         ~is_positive:(Q.sign q > 0)
         ~is_negative:(Q.sign q < 0)

let add env uf _r term =
  if not (Options.get_smt_lib_fpa ())
  then env, Uf.domains uf, []
  else
    let { E.f; ty; _ } = E.term_view term in
    match ty with
    | Ty.Tfloat (eb, sb) ->
      let env =
        if
          not
            (IntPairSet.mem (eb, sb) env.pending_types
            || Hashtbl.mem env.literals_cache (eb, sb))
        then
          { env with pending_types = IntPairSet.add (eb, sb) env.pending_types }
        else env
      in
      let env =
        match f with
        | Sy.Float v ->
          { env with
            pending_literals =
              fp_literal_facts eb sb term v @ env.pending_literals
          }
        | _ -> env
      in
      env, Uf.domains uf, []
    | _ -> env, Uf.domains uf, []

let assume env uf la =
  if not (Options.get_smt_lib_fpa ())
  then env, Uf.domains uf, { Sig_rel.assume = []; remove = [] }
  else
    let prec_facts =
      IntPairSet.fold
        (fun (eb, sb) acc -> type_literal_facts env eb sb @ acc)
        env.pending_types []
    in
    let eval_facts =
      List.map (fun (lhs, rhs) -> mk_eq_fact lhs rhs) env.pending_literals
    in
    let env =
      { env with pending_types = IntPairSet.empty; pending_literals = [] }
    in
    let env, pred_facts =
      List.fold_left
        (fun (env, acc) (_ra, root, ex, _orig) ->
          match root with
          | None -> env, acc
          | Some a -> (
            (* TODO: handle negative predicates, maybe use a domain that keeps
               information about what the floating-point value can be? that way
               if we learn that is_positive(x) is false, if is_zero(x) is true,
               then we can propagate that x = -0 *)
            match E.lit_view a with
            | E.Pred (t, false) ->
              let env, facts = process_pred env ex t in
              env, facts @ acc
            | _ -> env, acc))
        (env, []) la
    in
    ( env,
      Uf.domains uf,
      { Sig_rel.assume = prec_facts @ eval_facts @ pred_facts; remove = [] } )

let query _ _ _ = Th_util.Unknown

let case_split _env _uf ~for_model:_ = []

let optimizing_objective _env _uf _o = None

let new_terms _ = E.Set.empty

let instantiate ~do_syntactic_matching:_ _ env _ _ = env, []

let assume_th_elt t _ _ = t
