(library
  (name       FmSimplexPlugin)
  (libraries  AltErgoLib)
  (modules    Simplex Simplex_cache FmSimplexIneqs)
)

(install
  (package alt-ergo-free)
  (section share)
  (files
    (FmSimplexPlugin.cma as plugins/fm-simplex-plugin.cma)
    (FmSimplexPlugin.cmxs as plugins/fm-simplex-plugin.cmxs)
  )
)
