#!/bin/sh

git_repo=`git rev-parse --show-toplevel`
cd $git_repo/rsc/extra

res=`./check_style.sh`
echo $res

if [ "$res" = "All files have correct style" ] ; then
	./check_indentation.sh
	exit $?
else
  exit 1
fi
