name: CI

on:
  push:
  pull_request:

# Restrict the GITHUB_TOKEN
permissions: {}

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-shell --run 'make runtest-ci'
