name: CI

on:
  push:
  pull_request:

# Restrict the GITHUB_TOKEN
permissions: {}

jobs:
  check:
    matrix:
      os:
        - macos-latest
        - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-shell --run 'make runtest-ci'
